# bootstrap.yml - Configuración para conectar con Config Server
spring:
  application:
    name: consul-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6
        multiplier: 1.1
        max-interval: 2000
      request-connect-timeout: 5000
      request-read-timeout: 5000
      username: ${CONFIG_SERVER_USERNAME:}
      password: ${CONFIG_SERVER_PASSWORD:}
      label: ${CONFIG_SERVER_LABEL:main}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
  endpoint:
    health:
      show-details: always



logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"